# Generated by Django 6.0 on 2025-12-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flo_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
            ],
        ),
    ]
